[package]
name = "inkjsrsgd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "*"
inkjsrs = { path = "../inkjsrs" }
dashmap = "*"
serde_json = "*"

[lib]
crate-type = ["cdylib"]